### ISSUE TITLE
Integrate Godot Headless Server with Nakama

### ISSUE THREAD

**Issue by portwatcher** [portwatcher/blog-comments#32]
https://juryquinn.com/post/technology/2023-01-04

**Comment by aliotadi** [comment]
Thank you for this amazing doc you shared with the community =D you are a life saver.
i streamed reviewing your doc in twitch, if you would like to follow: https://www.twitch.tv/alistechtails
i'm new to this so any feedback will be much appretiated.
also your comment input section is not working i wrote my comment in notepad and copy/pasted in here.

**Comment by portwatcher** [comment]
> @aliotadi
> Thank you for this amazing doc you shared with the community =D you are a life saver.
> i streamed reviewing your doc in twitch, if you would like to follow: https://www.twitch.tv/alistechtails
> i'm new to this so any feedback will be much appretiated.
> also your comment input section is not working i wrote my comment in notepad and copy/pasted in here.

Though I have been developing many kinds of applications for years, I'm also new to gamedev, even new to English writing.
So I'm glad it helps!
